name: Warp CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Setup Cairo
        uses: ./.github/actions/set-up-cairo

      - name: Install dependencies
        run: make

      - name: Test code compilation
        run: make test_compilation

      - name: Test code execution
        run: |
          yarn testnet &
          make test_execution
