name: Warp CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Setup Cairo
        uses: ./.github/actions/set-up-cairo

      - name: Install dependencies
        run: yarn

      - name: Project compilation
        run: yarn tsc

      - name: Test code compilation
        run: bin/warp test

      - name: Test code execution
        run: |
          yarn testnet &
          yarn test
